name: CI

on:
  push:
    branches: [master]

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
      - uses: actions/checkout@v2

      - name: Install dependency
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_API_KEY }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: True
